title: Nordegraf's Blog
email: conen@stud.uni-frankfurt.de
description: >-
  Nordegraf's Personal Blog
baseurl: "/blog"
url: "https://nordegraf.github.io/blog/"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-gist

sass:
  sass_dir: _sass
  style: compressed

paginate: 5

exclude:
  - Gemfile
  - Gemfile.lock

permalink: pretty

collections:
  pages:
    output: true
    permalink: /:name


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
